### ISSUE TITLE
error with mismatched sizes

### ISSUE THREAD

**Issue by rsolari** [SonjaKT/housing_model#7]
I'm trying to simulate these 17 renters and 12 houses, but I get an error:

```
> python simulate.py
input number of renters with minimum housing score 1: 10
input number of renters with minimum housing score 2: 2
input number of renters with minimum housing score 3: 2
input number of renters with minimum housing score 4: 2
input number of renters with minimum housing score 5: 1
input number of housing units with score 1: 3
input number of housing units with score 2: 3
input number of housing units with score 3: 3
input number of housing units with score 4: 3
input number of housing units with score 5: 3
Traceback (most recent call last):
  File "simulate.py", line 41, in <module>
    user_input()
  File "simulate.py", line 27, in user_input
    mod = model.HousingModel(renters, houses)
  File "/src/housing_model/model.py", line 15, in __init__
    hm.stable_match(self.renters, self.houses)
  File "/src/housing_model/house_match.py", line 30, in stable_match
    for house in sorted(random.sample(houses, k), reverse=True):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 321, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population
```

**Comment by mattlichti** [comment]
I fixed it. The error was caused because the matching algorithm can't pick a random sample of 20 houses if there were less than 20 houses. Now it each renter consider all of the houses if there are less than 20. We usually simulated with a thousand or so so the error didn't come up.

**Comment by rsolari** [comment]
Thanks matt!
